@startuml
!include https://raw.githubusercontent.com/plantuml-stdlib/C4-PlantUML/master/C4_Context.puml

title Orders System - Context

Person(customer, 'Customer', 'Пользователь, оформляющий заказ')
System(orderSystem, 'Order System', 'Система обработки заказов')

System_Ext(paymentSystem, 'Payment System', 'Система платежей')
System_Ext(emailSystem, 'Email System', 'Система уведомлений')

Rel(customer, orderSystem, 'Создает заказ', 'HTTPS')
Rel(orderSystem, paymentSystem, 'Запрос на обработку платежа', 'HTTPS')
Rel(orderSystem, emailSystem, 'Рассылка уведомлений', 'HTTP')

@enduml